// automatically generated by the FlatBuffers compiler, do not modify

package common

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Vec2d struct {
	_tab flatbuffers.Struct
}

func (rcv *Vec2d) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Vec2d) X() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Vec2d) MutateX(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Vec2d) Y() int32 {
	return rcv._tab.GetInt32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *Vec2d) MutateY(n int32) bool {
	return rcv._tab.MutateInt32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func CreateVec2d(builder *flatbuffers.Builder, x int32, y int32) flatbuffers.UOffsetT {
	builder.Prep(4, 8)
	builder.PrependInt32(y)
	builder.PrependInt32(x)
	return builder.Offset()
}
